version: '3.6'

services:
  backend:
    build:
      context: ./backend
    restart: unless-stopped
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - 8000:8000
    env_file:
      - ./backend/.env
    networks:
      - my_network

  frontend:
    build:
      context: ./frontend
    command: yarn run dev
    restart: unless-stopped
    volumes:
      - ./frontend:/app
    ports:
      - 5173:5173
    env_file:
      - ./frontend/.env
    networks:
      - my_network

networks:
  my_network:
    name: my_network
